version: '3.8'

services:
  app:
    build: .
    container_name: spring-app
    environment:
      - EXCHANGE_API_KEY=${EXCHANGE_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./target:/app

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exchange_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
