spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

  exchange:
    rate:
      api:
        url_for_API: https://openexchangerates.org/api/latest.json?app_id=
        key: ea2968816b464fd786e10b7e47d85911

