spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect

  exchange:
    rate:
      api:
        url: "https://openexchangerates.org/api/latest.json?app_id=${EXCHANGE_API_KEY}"

  logging:
    level:
      org.springframework: DEBUG


